### PR TITLE
Remove sha256 due to DNS limitation

### PR DESCRIPTION
**Pull request by jcbf**

### CODE REVIEW

**Comment by steadramon** [comment]
Sorry I should have really excluded this in the last commit.

Out of curiosity are you using public BLs or a personal one?

**Comment by jcbf** [comment]
I'm setting up one. 
Instead of using just the hash I'm thinking about adding the query with other information, like content-type.
Something like  base58($ctype).$hash.$rbl_zone or even more data like client ip,filename and/or file extension.

**Comment by steadramon** [comment]
Ohh I like the idea - could be a similar setup to the ClamAV hdb and hsb files - they have the format hash:filesize which could easily be translated to $hash.$filesize.$zone ... 
Keep me posted on any updates

**Comment by steadramon** [comment]
oh and do let me know if I can be of any assistance

**Pull request merged**
